KVHero = {
        --字段名                        --注释                                          --控件名                        --控件参数                       --默认值                       --前置

    Normal = {
        {"BoundsHullName", "BoundsHullName", "kvdrop", "BoundsHullName", "DOTA_HULL_SIZE_HERO"},
        {"BountyGoldMax", "BountyGoldMax", "kvnumber", 1, 0},
        {"BountyGoldMin", "BountyGoldMin", "kvnumber", 1, 0},
        {"BountyXP", "BountyXP", "kvnumber", 1, 0},
        {"Enabled", "Enabled", "kvbool", nil, 1},

        {"HasAggressiveStance", "HasAggressiveStance", "kvbool", nil, 1},
        {"HasInventory", "HasInventory", "kvbool", nil, 1},
        {"HealthBarOffset", "HealthBarOffset", "kvbool", nil, 170},
        
        {"HeroID", "HeroID", "kvnumber", 1, 56},
        {"HeroOrderID", "HeroOrderID", "kvnumber", 1, 68},
        {"HeroPool1", "HeroPool1", "kvnumber", 1, 1},
        {"HeroPool2", "HeroPool2", "kvnumber", 1, 1},

        {"Level", "Level", "kvnumber", 1, 1},
        {"LoadoutScale", "LoadoutScale", "kvnumber", 0.1, 0.750000},
        {"VisionDaytimeRange", "VisionDaytimeRange", "kvnumber", 100, 1800},
        {"VisionNighttimeRange", "VisionNighttimeRange", "kvnumber", 100, 800},

        {"UnitRelationshipClass", "UnitRelationshipClass", "kvdrop", "UnitRelationshipClass", "DOTA_NPC_UNIT_RELATIONSHIP_TYPE_HERO"},
        --{"Team", "Team", "kvinput", "Bad"},
        {"TeamName", "TeamName", "kvdrop", "Teams", "DOTA_TEAM_BADGUYS"},
        {"RingRadius", "RingRadius", "kvnumber", 10, 70},
        
    },
    Show = {
        {"HeroGlowColor", "HeroGlowColor", "kvinput", nil, "205 58 0"},
        {"SoundSet", "SoundSet", "kvinput", nil, "Hero_Clinkz"},
        {"ModelScale", "ModelScale", "kvnumber", 0.1, 0.650000},
        {"Model", "Model", "kvinput", nil, "models/heroes/clinkz/clinkz.vmdl"},
        {"Model1", "Model1", "kvinput", nil, "models/heroes/nightstalker/nightstalker_night.vmdl"},
        {"Model2", "Model2", "kvinput", nil, "models/heroes/tiny/tiny_03/tiny_03.vmdl"},
        {"Model3", "Model3", "kvinput", nil, "models/heroes/tiny/tiny_04/tiny_04.vmdl"},
        {"IdleExpression", "IdleExpression", "kvinput", nil, "scenes/clinkz/clinkz_exp_idle_01.vcd"},
        {"IdleSoundLoop", "IdleSoundLoop", "kvinput", nil, "Hero_Clinkz.IdleLoop"},
        {"VoiceBackgroundSound", "VoiceBackgroundSound", "kvinput", nil, ""},
        {"VoiceFile", "VoiceFile", "kvinput", nil, "soundevents/voscripts/game_sounds_vo_clinkz.vsndevts"},
        {"GameSoundsFile", "GameSoundsFile", "kvinput", nil, "soundevents/game_sounds_heroes/game_sounds_clinkz.vsndevts"},
    },
    Ability = {
        {"Ability1", "Ability1", "kvinput", nil, "clinkz_strafe"},
        {"Ability2", "Ability2", "kvinput", nil, "clinkz_searing_arrows"},
        {"Ability3", "Ability3", "kvinput", nil, "clinkz_wind_walk"},
        {"Ability4", "Ability4", "kvinput", nil, "clinkz_burning_army"},
        {"Ability5", "Ability5", "kvinput", nil, "generic_hidden"},
        {"Ability6", "Ability6", "kvinput", nil, "clinkz_death_pact"},
        {"Ability7", "Ability7", "kvinput", nil, "nyx_assassin_unburrow"},
        {"Ability8", "Ability8", "kvinput", nil, "keeper_of_the_light_spirit_form_illuminate"},
        {"Ability9", "Ability9", "kvinput", nil, "keeper_of_the_light_spirit_form_illuminate_end"},
        {"Ability10", "Ability10", "kvinput", nil, "special_bonus_unique_clinkz_1"},
        {"Ability11", "Ability11", "kvinput", nil, "special_bonus_unique_clinkz_10"},
        {"Ability12", "Ability12", "kvinput", nil, "special_bonus_unique_clinkz_8"},
        {"Ability13", "Ability13", "kvinput", nil, "special_bonus_unique_clinkz_2"},
        {"Ability14", "Ability14", "kvinput", nil, "special_bonus_attack_range_125"},
        {"Ability15", "Ability15", "kvinput", nil, "special_bonus_unique_clinkz_12"},
        {"Ability16", "Ability16", "kvinput", nil, "special_bonus_unique_clinkz_4"},
        {"Ability17", "Ability17", "kvinput", nil, "special_bonus_unique_clinkz_3"},
        {"Ability18", "Ability18", "kvinput", nil, "special_bonus_unique_keeper_of_the_light"},
        {"Ability19", "Ability19", "kvinput", nil, "special_bonus_strength_20"},
        
        {"Ability20", "Ability20", "kvinput", nil, "special_bonus_unique_morphling_4"},
        {"Ability21", "Ability21", "kvinput", nil, "special_bonus_unique_morphling_6"},
        {"Ability22", "Ability22", "kvinput", nil, "special_bonus_unique_morphling_10"},
        {"Ability23", "Ability23", "kvinput", nil, "special_bonus_unique_invoker_2"},
        {"Ability24", "Ability24", "kvinput", nil, "special_bonus_unique_invoker_13"},
        {"Ability25", "Ability25", "kvinput", nil, "special_bonus_attributes"},

        {"AbilityDraftDisabled", "AbilityDraftDisabled", "kvbool", nil, 1},
        {"AbilityDraftIgnoreCount", "AbilityDraftIgnoreCount", "kvnumber", 1, 7},
        {"AbilityLayout", "AbilityLayout", "kvnumber", 1, 5},
        {"AbilityTalentStart", "AbilityTalentStart", "kvnumber", 1, 11},
    },
    Fight = {
        {"ArmorPhysical", "ArmorPhysical", "kvnumber", 1, 0},
        {"AttackAcquisitionRange", "AttackAcquisitionRange", "kvnumber", 1, 800},
        {"AttackAnimationPoint", "AttackAnimationPoint", "kvnumber", 0.1, 0.4},
        {"AttackCapabilities", "AttackCapabilities", "kvdrop", "AttackCap", "DOTA_UNIT_CAP_RANGED_ATTACK"},
        {"AttackDamageMax", "AttackDamageMax", "kvnumber", 1, 21},
        {"AttackDamageMin", "AttackDamageMin", "kvnumber", 1, 15},
        {"AttackDamageType", "AttackDamageType", "kvinput", nil, "DAMAGE_TYPE_ArmorPhysical"},
        {"AttackRange", "AttackRange", "kvnumber", 1, 600},
        {"AttackRangeBuffer", "AttackRangeBuffer", "kvnumber", 1, 550},
        {"AttackRate", "AttackRate", "kvnumber", 0.1, 1.700000},
        {"AttributeAgilityGain", "AttributeAgilityGain", "kvnumber", 0.1, 2.5},
        {"AttributeBaseAgility", "AttributeBaseAgility", "kvnumber", 1, 22},
        {"AttributeBaseIntelligence", "AttributeBaseIntelligence", "kvnumber", 1, 18},
        {"AttributeBaseStrength", "AttributeBaseStrength", "kvnumber", 1, 16},
        {"AttributeIntelligenceGain", "AttributeIntelligenceGain", "kvnumber", 0.1, 2.2},
        {"AttributePrimary", "AttributePrimary", "kvdrop", "Attributes", "DOTA_ATTRIBUTE_AGILITY"},
        {"AttributeStrengthGain", "AttributeStrengthGain", "kvnumber", 0.1, 2.000000},
        {"BaseAttackSpeed", "BaseAttackSpeed", "kvnumber", 1, 100},
        {"MagicalResistance", "MagicalResistance", "kvnumber", 1, 25},
        {"StatusHealth", "StatusHealth", "kvnumber", 1, 5000},
        {"StatusHealthRegen", "StatusHealthRegen", "kvnumber", 0.1, 0.25},
        {"StatusMana", "StatusMana", "kvnumber", 1, 5000},
        {"StatusManaRegen", "StatusManaRegen", "kvnumber", 1, 0},
        
        {"CombatClassAttack", "CombatClassAttack", "kvdrop", "CombatClassAttack", "DOTA_COMBAT_CLASS_ATTACK_HERO"},
        {"CombatClassDefend", "CombatClassDefend", "kvdrop", "CombatClassDefend", "DOTA_COMBAT_CLASS_DEFEND_HERO"},

        {"MovementCapabilities", "MovementCapabilities", "kvdrop", "MovementCap", "DOTA_UNIT_CAP_MOVE_GROUND"},
        {"MovementSpeed", "MovementSpeed", "kvnumber", 1, 290},
        {"MovementTurnRate", "MovementTurnRate", "kvnumber", 0.1, 0.700000},

        {"ProjectileModel", "ProjectileModel", "kvinput", nil, "particles/units/heroes/hero_clinkz/clinkz_base_attack.vpcf"},
        {"ProjectileSpeed", "ProjectileSpeed", "kvnumber", 1, 900},
    },
    Unusual = {
        {"ARDMDisabled", "ARDMDisabled", "kvnumber", 1, 0},
        {"AlternateLoadoutScale", "AlternateLoadoutScale", "kvnumber", 0.1, 0.770000},
        {"new_player_enable", "new_player_enable", "kvnumber", 1, 1},
        {"particle_folder", "particle_folder", "kvinput", "particles/units/heroes/hero_clinkz"},
        {"workshop_guide_name", "workshop_guide_name", "kvinput", "Clinkz"},
        {"MaxModelScaleMultiplier", "MaxModelScaleMultiplier", "kvnumber", 0.1, 1.22},
        {"NameAliases", "NameAliases", "kvinput", "Tresdin,Legion"},
        {"NewHero", "NewHero", "kvnumber", 1, 0},
        {"NoCombine", "NoCombine", "kvnumber", 1, 1},
        {"PickSound", "PickSound", "kvinput", "clinkz_clinkz_spawn_01"},
        {"Press", "Press", "kvnumber", 1, 1},
        {"RareIdleExpression", "RareIdleExpression", "kvinput", "scenes/primal_beast/primal_beast_exp_idle_02.vcd"},
        {"ReleaseTimestamp", "ReleaseTimestamp", "kvnumber", 1, 1509390000},
        {"Role", "Role", "kvinput", "Carry,Escape,Pusher"},
        {"Rolelevels", "Rolelevels", "kvinput", "2,3,1"},
        {"ShowcasePlayIdleExpression", "ShowcasePlayIdleExpression", "kvnumber", 1, 0},
        {"SimilarHeroes", "SimilarHeroes", "kvinput", "32,44,46"},
        {"SpectatorLoadoutScale", "SpectatorLoadoutScale", "kvnumber", 0.1, 0.8},
        {"TransformedLoadoutScale", "TransformedLoadoutScale", "kvnumber", 0.1, 1.13},
        {"VersusScale", "VersusScale", "kvnumber", 0.1, 0.790000},
        {"CMEnabled", "CMEnabled", "kvnumber", 1, 1},
        {"CMTournamentIgnore", "CMTournamentIgnore", "kvnumber", 1, 0},
        {"Complexity", "Complexity", "kvnumber", 1, 2},
        {"GibTintColor", "GibTintColor", "kvinput", "166 29 17 255"},
        {"GibType", "GibType", "kvinput", "default"},
        {"HeroSelectSoundEffect", "HeroSelectSoundEffect", "kvinput", "Hero_Clinkz.Pick"},
        {"HeroUnlockOrder", "HeroUnlockOrder", "kvnumber", 1, 2},
        {"BanSound", "BanSound", "kvinput", "clinkz_clinkz_anger_08"},
        {"BotForceSelection", "BotForceSelection", "kvnumber", 1, 0},
        {"BotImplemented", "BotImplemented", "kvnumber", 1, 0},
        {"LastHitChallengeRival", "LastHitChallengeRival", "kvinput", "npc_dota_hero_windrunner"},
        {"Legs", "Legs", "kvnumber", 1, 6},
    },
}